language: ruby
rvm:
  - 1.8.7
script: "rake spec_prep spec"
branches:
  only:
    - master
env:
  - PUPPET_VERSION=2.6.17
  - PUPPET_VERSION=2.7.19
  - PUPPET_VERSION=3.0.1
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.perl.org#puppet"
